// src/domains/theme/ThemePanel.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';

import { ChipsButton, ChipsInput, ChipsSelect, ChipsSwitch } from '@chips/components';

import { useI18n } from '@/composables/use-i18n';
import { ecosystemSettingsService } from '@/services/ecosystem-settings-service';
import type { ThemeOption } from '@/types';

const { t } = useI18n();
const loading = ref(false);
const saving = ref(false);
const error = ref('');
const themes = ref<ThemeOption[]>([]);
const currentThemeId = ref('default');

const installPath = ref('');
const installOverwrite = ref(false);
const uninstallThemeId = ref('');

const themeOptions = computed(() =>
  themes.value.map((theme) => ({
    value: theme.id,
    label: theme.version ? `${theme.name} (${theme.version})` : theme.name
  }))
);

async function refresh(): Promise<void> {
  loading.value = true;
  error.value = '';

  try {
    const [themeList, activeTheme] = await Promise.all([
      ecosystemSettingsService.listThemeOptions(),
      ecosystemSettingsService.getCurrentThemeId()
    ]);

    themes.value = themeList;
    currentThemeId.value = activeTheme;
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    loading.value = false;
  }
}

async function applyTheme(): Promise<void> {
  saving.value = true;
  error.value = '';

  try {
    await ecosystemSettingsService.applyTheme(currentThemeId.value);
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    saving.value = false;
  }
}

async function installTheme(): Promise<void> {
  if (!installPath.value) {
    return;
  }

  saving.value = true;
  error.value = '';

  try {
    await ecosystemSettingsService.installTheme(installPath.value, installOverwrite.value);
    installPath.value = '';
    installOverwrite.value = false;
    await refresh();
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    saving.value = false;
  }
}

async function uninstallTheme(): Promise<void> {
  if (!uninstallThemeId.value) {
    return;
  }

  saving.value = true;
  error.value = '';

  try {
    await ecosystemSettingsService.uninstallTheme(uninstallThemeId.value);
    uninstallThemeId.value = '';
    await refresh();
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    saving.value = false;
  }
}

function handleThemeChange(value: string | string[]): void {
  currentThemeId.value = Array.isArray(value) ? String(value[0] ?? '') : String(value);
}

onMounted(async () => {
  await refresh();
});
</script>

<template>
  <section class="chips-settings-panel">
    <header class="chips-settings-panel__header">
      <div>
        <h2 class="chips-settings-panel__title">{{ t('i18n.plugin.694001') }}</h2>
        <p class="chips-settings-panel__description">{{ t('i18n.plugin.694002') }}</p>
      </div>
      <ChipsButton variant="secondary" :loading="loading" @click="refresh">{{ t('i18n.plugin.694003') }}</ChipsButton>
    </header>

    <div v-if="error" class="chips-settings-alert chips-settings-alert--error">{{ error }}</div>

    <div class="chips-settings-card">
      <h3 class="chips-settings-card__title">{{ t('i18n.plugin.694004') }}</h3>
      <div class="chips-settings-card__toolbar">
        <ChipsSelect
          :model-value="currentThemeId"
          :options="themeOptions"
          @update:model-value="handleThemeChange"
        />
        <ChipsButton variant="primary" :loading="saving" @click="applyTheme">{{ t('i18n.plugin.694005') }}</ChipsButton>
      </div>
    </div>

    <div class="chips-settings-card">
      <h3 class="chips-settings-card__title">{{ t('i18n.plugin.694006') }}</h3>
      <div class="chips-settings-card__toolbar">
        <ChipsInput v-model="installPath" :placeholder="t('i18n.plugin.694007')" />
        <ChipsSwitch v-model="installOverwrite">{{ t('i18n.plugin.694008') }}</ChipsSwitch>
        <ChipsButton variant="secondary" :loading="saving" @click="installTheme">{{ t('i18n.plugin.694009') }}</ChipsButton>
      </div>
    </div>

    <div class="chips-settings-card">
      <h3 class="chips-settings-card__title">{{ t('i18n.plugin.694010') }}</h3>
      <div class="chips-settings-card__toolbar">
        <ChipsInput v-model="uninstallThemeId" :placeholder="t('i18n.plugin.694011')" />
        <ChipsButton variant="danger" :loading="saving" @click="uninstallTheme">{{ t('i18n.plugin.694012') }}</ChipsButton>
      </div>
    </div>
  </section>
</template>

// src/features/panels/ThemePanel.tsx
import { useEffect, useState } from 'react';
import { Button, ChipsFileUpload, Input, Select, Switch } from '@chips/component-library';

import { ecosystemSettingsService } from '@/services/ecosystem-settings-service';
import type { ThemeOption } from '@/types';
import { useI18n } from '@/i18n';
import { ErrorAlert } from '@/features/shared/ErrorAlert';
import { toDisplayError, type DisplayError } from '@/utils/error';

export function ThemePanel() {
  const { t } = useI18n();
  const [themes, setThemes] = useState<ThemeOption[]>([]);
  const [currentThemeId, setCurrentThemeId] = useState('');
  const [installFile, setInstallFile] = useState<File | null>(null);
  const [installOverwrite, setInstallOverwrite] = useState(false);
  const [uninstallThemeId, setUninstallThemeId] = useState('');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<DisplayError | null>(null);

  const refresh = async (): Promise<void> => {
    setLoading(true);
    setError(null);
    try {
      const [nextThemes, activeTheme] = await Promise.all([
        ecosystemSettingsService.listThemeOptions(),
        ecosystemSettingsService.getCurrentThemeId()
      ]);
      setThemes(nextThemes);
      setCurrentThemeId(activeTheme);
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setLoading(false);
    }
  };

  const applyTheme = async (): Promise<void> => {
    setSaving(true);
    setError(null);
    try {
      await ecosystemSettingsService.applyTheme(currentThemeId);
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setSaving(false);
    }
  };

  const installTheme = async (): Promise<void> => {
    if (!installFile) {
      setError({
        code: 'FILE_READ_FAILED',
        message: t('i18n.plugin.699027'),
        rawMessage: t('i18n.plugin.699027')
      });
      return;
    }

    setSaving(true);
    setError(null);
    try {
      const packagePath = await ecosystemSettingsService.resolveInstallPackagePath(installFile);
      await ecosystemSettingsService.installTheme(packagePath, installOverwrite);
      setInstallFile(null);
      setInstallOverwrite(false);
      await refresh();
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setSaving(false);
    }
  };

  const uninstallTheme = async (): Promise<void> => {
    if (!uninstallThemeId) {
      return;
    }

    setSaving(true);
    setError(null);
    try {
      await ecosystemSettingsService.uninstallTheme(uninstallThemeId);
      setUninstallThemeId('');
      await refresh();
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  return (
    <section className="chips-settings-panel">
      <header className="chips-settings-panel__header">
        <div>
          <h2 className="chips-settings-panel__title">{t('i18n.plugin.694001')}</h2>
          <p className="chips-settings-panel__description">{t('i18n.plugin.694002')}</p>
        </div>
        <Button onClick={() => void refresh()} disabled={loading}>
          {t('i18n.plugin.694003')}
        </Button>
      </header>

      <ErrorAlert error={error} summaryKey="i18n.plugin.691008" />

      <article className="chips-settings-card">
        <h3 className="chips-settings-card__title">{t('i18n.plugin.694004')}</h3>
        <div className="chips-settings-card__toolbar">
          <Select
            value={currentThemeId}
            options={themes.map((theme) => ({
              value: theme.id,
              label: theme.version ? `${theme.name} (${theme.version})` : theme.name
            }))}
            onValueChange={(value) => setCurrentThemeId(value ?? '')}
          />
          <Button onClick={() => void applyTheme()} disabled={saving}>
            {t('i18n.plugin.694005')}
          </Button>
        </div>
      </article>

      <article className="chips-settings-card">
        <h3 className="chips-settings-card__title">{t('i18n.plugin.694006')}</h3>
        <p className="chips-settings-card__meta">{t('i18n.plugin.699026')}</p>
        <div className="chips-settings-form">
          <ChipsFileUpload
            value={installFile}
            acceptExtensions={['.cpk']}
            onChange={setInstallFile}
            onError={(uploadError) => setError(toDisplayError(uploadError))}
          />
          <Switch checked={installOverwrite} onCheckedChange={setInstallOverwrite}>
            {t('i18n.plugin.694008')}
          </Switch>
          <div className="chips-settings-panel__actions">
            <Button
              data-testid="theme-install-button"
              onClick={() => void installTheme()}
              disabled={saving || installFile === null}
            >
              {t('i18n.plugin.694009')}
            </Button>
          </div>
        </div>
      </article>

      <article className="chips-settings-card">
        <h3 className="chips-settings-card__title">{t('i18n.plugin.694010')}</h3>
        <div className="chips-settings-card__toolbar">
          <Input
            aria-label="theme-uninstall-id"
            value={uninstallThemeId}
            onChange={(event) => setUninstallThemeId(event.target.value)}
            placeholder={t('i18n.plugin.694011')}
          />
          <Button onClick={() => void uninstallTheme()} disabled={saving || uninstallThemeId.length === 0}>
            {t('i18n.plugin.694012')}
          </Button>
        </div>
      </article>
    </section>
  );
}
