// src/features/panels/FileSystemPanel.tsx
import { useEffect, useState } from 'react';
import { Button, Input, Select } from '@chips/component-library';

import { ecosystemSettingsService } from '@/services/ecosystem-settings-service';
import type { WorkspaceExchangePolicy } from '@/types';
import { useI18n } from '@/i18n';
import { ErrorAlert } from '@/features/shared/ErrorAlert';
import { toDisplayError, type DisplayError } from '@/utils/error';

export function FileSystemPanel() {
  const { t } = useI18n();
  const [workspacePath, setWorkspacePath] = useState('');
  const [policy, setPolicy] = useState<WorkspaceExchangePolicy>({
    mode: 'copy',
    conflict: 'rename'
  });
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<DisplayError | null>(null);

  const refresh = async (): Promise<void> => {
    setLoading(true);
    setError(null);
    try {
      const [path, nextPolicy] = await Promise.all([
        ecosystemSettingsService.getWorkspacePath(),
        ecosystemSettingsService.getWorkspaceExchangePolicy()
      ]);
      setWorkspacePath(path);
      setPolicy(nextPolicy);
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setLoading(false);
    }
  };

  const savePath = async (): Promise<void> => {
    setSaving(true);
    setError(null);
    try {
      await ecosystemSettingsService.setWorkspacePath(workspacePath);
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setSaving(false);
    }
  };

  const savePolicy = async (): Promise<void> => {
    setSaving(true);
    setError(null);
    try {
      await ecosystemSettingsService.setWorkspaceExchangePolicy(policy);
    } catch (reason: unknown) {
      setError(toDisplayError(reason));
    } finally {
      setSaving(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  return (
    <section className="chips-settings-panel">
      <header className="chips-settings-panel__header">
        <div>
          <h2 className="chips-settings-panel__title">{t('i18n.plugin.696001')}</h2>
          <p className="chips-settings-panel__description">{t('i18n.plugin.696002')}</p>
        </div>
        <Button onClick={() => void refresh()} disabled={loading}>
          {t('i18n.plugin.696003')}
        </Button>
      </header>

      <ErrorAlert error={error} summaryKey="i18n.plugin.691008" />

      <article className="chips-settings-card">
        <h3 className="chips-settings-card__title">{t('i18n.plugin.696004')}</h3>
        <div className="chips-settings-card__toolbar">
          <Input
            aria-label={t('i18n.plugin.696004')}
            value={workspacePath}
            onChange={(event) => setWorkspacePath(event.target.value)}
            placeholder={t('i18n.plugin.696005')}
          />
          <Button onClick={() => void savePath()} disabled={saving}>
            {t('i18n.plugin.696006')}
          </Button>
        </div>
      </article>

      <article className="chips-settings-card">
        <h3 className="chips-settings-card__title">{t('i18n.plugin.696007')}</h3>
        <div className="chips-settings-card__toolbar">
          <Select
            label={t('i18n.plugin.696008')}
            value={policy.mode}
            options={[
              { value: 'copy', label: t('i18n.plugin.696011') },
              { value: 'link', label: t('i18n.plugin.696012') }
            ]}
            onValueChange={(value) =>
              setPolicy((current) => ({
                ...current,
                mode: value === 'link' ? 'link' : 'copy'
              }))
            }
          />
          <Select
            label={t('i18n.plugin.696009')}
            value={policy.conflict}
            options={[
              { value: 'rename', label: t('i18n.plugin.696013') },
              { value: 'skip', label: t('i18n.plugin.696014') },
              { value: 'overwrite', label: t('i18n.plugin.696015') }
            ]}
            onValueChange={(value) =>
              setPolicy((current) => ({
                ...current,
                conflict: value === 'overwrite' || value === 'skip' ? value : 'rename'
              }))
            }
          />
          <Button onClick={() => void savePolicy()} disabled={saving}>
            {t('i18n.plugin.696010')}
          </Button>
        </div>
      </article>
    </section>
  );
}

// src/domains/filesystem/FileSystemPanel.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';

import { ChipsButton, ChipsInput, ChipsSelect } from '@chips/components';

import { useI18n } from '@/composables/use-i18n';
import { ecosystemSettingsService } from '@/services/ecosystem-settings-service';
import type { WorkspaceExchangePolicy } from '@/types';

const { t } = useI18n();
const loading = ref(false);
const saving = ref(false);
const error = ref('');

const workspacePath = ref('');
const policy = ref<WorkspaceExchangePolicy>({
  mode: 'copy',
  conflict: 'rename'
});

const modeOptions = [
  { value: 'copy', label: 'copy' },
  { value: 'link', label: 'link' }
];

const conflictOptions = [
  { value: 'rename', label: 'rename' },
  { value: 'overwrite', label: 'overwrite' },
  { value: 'skip', label: 'skip' }
];

async function refresh(): Promise<void> {
  loading.value = true;
  error.value = '';

  try {
    const [path, exchangePolicy] = await Promise.all([
      ecosystemSettingsService.getWorkspacePath(),
      ecosystemSettingsService.getWorkspaceExchangePolicy()
    ]);

    workspacePath.value = path;
    policy.value = exchangePolicy;
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    loading.value = false;
  }
}

async function savePath(): Promise<void> {
  saving.value = true;
  error.value = '';

  try {
    await ecosystemSettingsService.setWorkspacePath(workspacePath.value);
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    saving.value = false;
  }
}

async function savePolicy(): Promise<void> {
  saving.value = true;
  error.value = '';

  try {
    await ecosystemSettingsService.setWorkspaceExchangePolicy(policy.value);
  } catch (reason: unknown) {
    error.value = reason instanceof Error ? reason.message : String(reason);
  } finally {
    saving.value = false;
  }
}

function handleModeChange(value: string | string[]): void {
  const resolved = Array.isArray(value) ? value[0] : value;
  policy.value = {
    ...policy.value,
    mode: resolved === 'link' ? 'link' : 'copy'
  };
}

function handleConflictChange(value: string | string[]): void {
  const resolved = Array.isArray(value) ? value[0] : value;
  const conflict =
    resolved === 'overwrite' || resolved === 'skip' || resolved === 'rename' ? resolved : 'rename';
  policy.value = {
    ...policy.value,
    conflict
  };
}

onMounted(async () => {
  await refresh();
});
</script>

<template>
  <section class="chips-settings-panel">
    <header class="chips-settings-panel__header">
      <div>
        <h2 class="chips-settings-panel__title">{{ t('i18n.plugin.696001') }}</h2>
        <p class="chips-settings-panel__description">{{ t('i18n.plugin.696002') }}</p>
      </div>
      <ChipsButton variant="secondary" :loading="loading" @click="refresh">{{ t('i18n.plugin.696003') }}</ChipsButton>
    </header>

    <div v-if="error" class="chips-settings-alert chips-settings-alert--error">{{ error }}</div>

    <div class="chips-settings-card">
      <h3 class="chips-settings-card__title">{{ t('i18n.plugin.696004') }}</h3>
      <div class="chips-settings-card__toolbar">
        <ChipsInput v-model="workspacePath" :placeholder="t('i18n.plugin.696005')" />
        <ChipsButton variant="primary" :loading="saving" @click="savePath">{{ t('i18n.plugin.696006') }}</ChipsButton>
      </div>
    </div>

    <div class="chips-settings-card">
      <h3 class="chips-settings-card__title">{{ t('i18n.plugin.696007') }}</h3>
      <div class="chips-settings-form">
        <label class="chips-settings-form__field">
          <span class="chips-settings-form__label">{{ t('i18n.plugin.696008') }}</span>
          <ChipsSelect :model-value="policy.mode" :options="modeOptions" @update:model-value="handleModeChange" />
        </label>
        <label class="chips-settings-form__field">
          <span class="chips-settings-form__label">{{ t('i18n.plugin.696009') }}</span>
          <ChipsSelect
            :model-value="policy.conflict"
            :options="conflictOptions"
            @update:model-value="handleConflictChange"
          />
        </label>
      </div>
      <div class="chips-settings-card__toolbar">
        <ChipsButton variant="secondary" :loading="saving" @click="savePolicy">{{ t('i18n.plugin.696010') }}</ChipsButton>
      </div>
    </div>
  </section>
</template>
